service:
  name: api
  version: ">=1.5"

plugins:
  - serverless-dotenv-plugin
  - serverless-offline
  - serverless-plugin-typescript

custom:
  allowedHeaders:
    - Accept
    - Content-Type
    - Content-Length
    - Authorization
    - X-Amz-Date
    - X-Api-Key
    - X-Amz-Security-Token
    - X-Amz-User-Agent

provider:
  name: aws
  runtime: nodejs12.x
  timeout: 5
  region: eu-west-1
  endpointType: regional

functions:
  graphql:
    handler: src/handler.graphqlHandler
    events:
      - http:
          path: graphql
          method: post
          cors:
            origin: "*"
            headers: ${self:custom.allowedHeaders}
      - http:
          path: graphql
          method: get
          cors:
            origin: "*"
            headers: ${self:custom.allowedHeaders}
