
name: Serverless Action

on:
  push:
    paths:
      - "api/**"
      - ".github/workflows/deploy-api.yml"
    branches: [master]
  # pull_request:
  #   paths:
  #     - "backend/**"
  #     - ".github/workflows/deploy.yml"
  #   branches: [master]

jobs:
  test:
    name: unit-tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Run tests
        run: cd api && npm run test:ci

  deploy:
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: cd api && npm ci

      - name: install serverless
        run: npm i -g serverless@2.1.0

      - name: Deploy to AWS
        run: cd api && serverless deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}